[build]
    command = "npm run build && npm run export"
    publish = "out"
Then add the export script to package.json;

"scripts": {
    "export": "next export"
},
Build settings for the netlify project;
Build command: npm run build && npm run export
Publish directory: out